os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

jobs:
  include:
    - stage: test
      before_script:
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - yarn global add @angular/cli
     script:
       - ng test --watch false
       - ng e2e
     stage: deploy
      before_install:
        - openssl aes-256-cbc -K $encrypted_f74f1974c608_key -iv $encrypted_f74f1974c608_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
        - if [ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
      script:
        - eval "$(ssh-agent -s)"
        - chmod 600 .travis/deploy_key.pem
        - ssh-add .travis/deploy_key.pem
        - mv -fv .travis/ssh_config ~/.ssh/config
        - git remote add dokku dokku@vps.kruczjak.pl:page-builder
        - git push dokku master


notifications:
  email:
    on_failure: change
    on_success: change
