language: node_js
node_js:
  - "6.9"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn global add @angular/cli

script:
  - ng test
  - ng e2e

notifications:
  email:
    on_failure: change
    on_success: change
